import React, {useEffect, useState} from 'react';
import {createRoot} from 'react-dom/client';
import './styles.css';
const API=import.meta.env.VITE_API_URL||'http://localhost:8000';
function App(){
  const [user,setUser]=useState(null),[result,setResult]=useState(null),[text,setText]=useState(''),[reports,setReports]=useState([]);
  const [login,setLogin]=useState({full_name:'',employee_id:'',role:'worker'}),[error,setError]=useState('');
  async function register(e){e.preventDefault();setError('');try{const r=await fetch(`${API}/users/register`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(login)});if(!r.ok)throw new Error();setUser(await r.json())}catch{setError('Cannot reach the safety database. Start the API, then try again.')}}
  useEffect(()=>{if(user)fetch(`${API}/reports`).then(r=>r.json()).then(setReports).catch(()=>setReports([]))},[user]);
  async function submit(e){e.preventDefault();const r=await fetch(`${API}/reports`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({reporter_id:user.id,reporter_name:user.full_name,site:'Duliajan Drill Pad 4',report_type:'Unsafe condition',narrative:text})});const saved=await r.json();setResult(saved);setReports([saved,...reports]);setText('')}
  if(!user)return <main className="login"><section><b>✦ HealthHive</b><h1>Every report deserves a safer response.</h1><p>Safety intelligence for SIF precursor reporting and triage.</p></section><form className="card" onSubmit={register}><h2>Enter workspace</h2><input placeholder="Full name" required value={login.full_name} onChange={e=>setLogin({...login,full_name:e.target.value})}/><input placeholder="Employee ID" required value={login.employee_id} onChange={e=>setLogin({...login,employee_id:e.target.value})}/><select value={login.role} onChange={e=>setLogin({...login,role:e.target.value})}><option value="worker">Worker</option><option value="supervisor">Supervisor</option></select><button>Register and continue</button>{error&&<small>{error}</small>}</form></main>;
  const visibleReports=user.role==='supervisor'?reports:reports.filter(r=>r.reporter_id===user.id);const high=reports.filter(r=>r.risk_level==='High').length;
  return <main className="workspace"><header><b>✦ HealthHive</b><span>{user.full_name} · {user.role}</span></header>{user.role==='supervisor'&&<section className="dashboard"><h1>Safety overview</h1><div className="metrics"><div>{high}<br/><small>Open high-risk reports</small></div><div>{reports.length}<br/><small>Reports in register</small></div><div>82%<br/><small>Closure verified</small></div></div><h2>Human review queue</h2><p>{high} high-priority reports require supervisor validation.</p></section>}<section className="card"><h2>New safety report</h2><form onSubmit={submit}><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Describe the hazard or near miss" required/><button>Analyse and save report</button></form>{result&&<p><b>{result.reference} saved · {result.risk_level} priority</b> · {result.iogp_rule||'Human review'} · confidence {result.confidence}%</p>}</section><section className="card"><h2>{user.role==='supervisor'?'Live report register':'Your report history'}</h2>{visibleReports.map(r=><p key={r.reference}><b>{r.reference}</b> · {r.site} · {r.risk_level} · {r.status}</p>)}</section></main>
}
createRoot(document.getElementById('root')).render(<App/>);
